yolo_model:

  config_file:
    name: yolov3-tiny-cows.cfg
  weight_file:
    name: yolov3-tiny-cows.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - cow
      - farmer
      - manure
